image: alpine
git:
  path: github.com/rajcisco/hello-world-1
script:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
clone:
  path: github.com/rajcisco/hello-world-1
build:
  image: alpine
  commands:
    - echo "build commands"
    - echo "no build command"
    - echo "no test command"
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
